import {
    faHome,
    faHeadphones,
    faGamepad,
    faBasketballBall,
    faShirt,
    faMasksTheater,
    faDumbbell,
    faBitcoinSign,
    faClover,
    faSatelliteDish,
    faClapperboard,
    faUserGraduate,
    faPodcast,
  
  } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

export const categories = [
    { name: 'New', icon: <FontAwesomeIcon color="red" icon={faHome}/>, },
    { name: 'JS Mastery', icon: <FontAwesomeIcon color="red" icon={faUserGraduate}/>, },
    { name: 'Coding', icon: <FontAwesomeIcon color="red" icon={faUserGraduate}/>, },
    { name: 'ReactJS', icon: <FontAwesomeIcon color="red" icon={faUserGraduate}/>, },
    { name: 'NextJS', icon: <FontAwesomeIcon color="red" icon={faUserGraduate}/>, },
    { name: 'Music', icon: <FontAwesomeIcon color="red" icon={faHeadphones}/> },
    { name: 'Education', icon: <FontAwesomeIcon color="red" icon={faUserGraduate}/>, },
    { name: 'Podcast', icon: <FontAwesomeIcon color="red" icon={faPodcast}/>, },
    { name: 'Movie', icon: <FontAwesomeIcon color="red" icon={faClapperboard}/>, },
    { name: 'Gaming', icon: <FontAwesomeIcon color="red" icon={faGamepad}/>, },
    { name: 'Live', icon: <FontAwesomeIcon color="red" icon={faSatelliteDish}/>, },
    { name: 'Sport', icon: <FontAwesomeIcon color="red" icon={faBasketballBall}/>, },
    { name: 'Fashion', icon: <FontAwesomeIcon color="red" icon={faShirt}/>, },
    { name: 'Beauty', icon: <FontAwesomeIcon color="red" icon={faClover}/>, },
    { name: 'Comedy', icon: <FontAwesomeIcon color="red" icon={faMasksTheater}/>, },
    { name: 'Gym', icon: <FontAwesomeIcon color="red" icon={faDumbbell}/>, },
    { name: 'Crypto', icon: <FontAwesomeIcon color="red" icon={faBitcoinSign}/>, },
    { name: 'New', icon: <FontAwesomeIcon color="red" icon={faHome}/>, },
    { name: 'JS Mastery', icon: <FontAwesomeIcon icon={faUserGraduate}/>, },
    { name: 'Coding', icon: <FontAwesomeIcon icon={faUserGraduate}/>, },
    { name: 'ReactJS', icon: <FontAwesomeIcon icon={faUserGraduate}/>, },
    { name: 'NextJS', icon: <FontAwesomeIcon inpm startcon={faUserGraduate}/>, },
    { name: 'Music', icon: <FontAwesomeIcon icon={faHeadphones}/> },
    { name: 'Education', icon: <FontAwesomeIcon icon={faUserGraduate}/>, },
    { name: 'Podcast', icon: <FontAwesomeIcon icon={faPodcast}/>, },
    { name: 'Movie', icon: <FontAwesomeIcon icon={faClapperboard}/>, },
    { name: 'Gaming', icon: <FontAwesomeIcon icon={faGamepad}/>, },
  ];
  